<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Starter.Tests</RootNamespace>
    <AssemblyName>Starter.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Starter\Starter.csproj" />
  </ItemGroup>
</Project>
